"""Initial migration

Revision ID: 0f603dccadda
Revises: 
Create Date: 2020-08-13 11:46:21.930555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f603dccadda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_english', sa.Text(), nullable=False),
    sa.Column('title_romanji', sa.Text(), nullable=True),
    sa.Column('others', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('url_image', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('start_date_year', sa.Integer(), nullable=True),
    sa.Column('nb_eps', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animes_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animes_genres_name'), 'animes_genres', ['name'], unique=True)
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['animes_genres.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'anime_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.drop_index(op.f('ix_animes_genres_name'), table_name='animes_genres')
    op.drop_table('animes_genres')
    op.drop_table('animes')
    # ### end Alembic commands ###
