"""Initial migration for thumbnail table

Revision ID: 7ed65e5d4d02
Revises: 
Create Date: 2021-09-05 12:24:00.528404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed65e5d4d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_hash', sa.Text(), nullable=False),
    sa.Column('thumbnail_sprite_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_host_hash'), 'thumbnail', ['host_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_host_hash'), table_name='thumbnail')
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
