version: '3.1'

services:
  back:
    build: .
    tty: true
    command: python serve.py
    network_mode: bridge
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=nekosama
