version: '3.1'

services:
  nekosamadb:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "nekosama"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    network_mode: bridge
    volumes:
      - nekosamadbdata:/var/lib/postgresql/data
  webapi:
    build: .
    tty: true
    command: python serve.py
    network_mode: bridge
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - nekosamadb
    environment:
      FLASK_APP: "nekosama"

volumes:
  nekosamadbdata:
