version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    network_mode: bridge
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - node.name=esn01
      - cluster.name=stanislavs-docker-cluster
      - cluster.initial_master_nodes=esn01
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
  webapi:
    build: .
    tty: true
    command: python serve.py
    network_mode: bridge
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - elasticsearch
    environment:
      FLASK_APP: "nekosama"

volumes:
  elasticsearch:
